In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import scipy as stats

In [ ]:
# 2. Load Dataset
df = pd.read_csv('/content/cleaned_car_MSR_data.csv')

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 11914 entries, 0 to 11913
Data columns (total 19 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Make                11914 non-null  object
 1   Model               11914 non-null  object
 2   Year                11914 non-null  int64
 3   Engine Fuel Type    11914 non-null  object
 4   Engine HP           11914 non-null  float64
 5   Engine Cylinders    11914 non-null  float64
 6   Transmission Type   11914 non-null  object
 7   Driven_Wheels       11914 non-null  object
 8   Number of Doors     11914 non-null  float64
 9   Market Category     11914 non-null  object
 10  Vehicle Size        11914 non-null  object
 11  Vehicle Style       11914 non-null  object
 12  highway MPG         11914 non-null  int64
 13  city mpg            11914 non-null  int64
 14  Popularity          11914 non-null  int64
 15  MSRP                11914 non-null  int64
 16  log_MSRP            11914 non-null  float64
 17  MSRP_per_Engine_HP  11914 non-null  float64
 18  HP_per_Cylinder     11914 non-null  float64
dtypes: float64(6), int64(5), object(8)
memory usage: 1.7+ MB

In [ ]:
df.head(5)

,Make,Model,Year,Engine Fuel Type,Engine HP,Engine Cylinders,Transmission Type,Driven_Wheels,Number of Doors,Market Category,Vehicle Size,Vehicle Style,highway MPG,city mpg,Popularity,MSRP,log_MSRP,MSRP_per_Engine_HP,HP_per_Cylinder
0,BMW,1 Series M,2011,premium unleaded (required),335.0,6.0,MANUAL,rear wheel drive,2.0,"Factory Tuner,Luxury,High-Performance",Compact,Coupe,26,19,3916,46135,10.739327,137.716418,55.833333
1,BMW,1 Series,2011,premium unleaded (required),300.0,6.0,MANUAL,rear wheel drive,2.0,"Luxury,Performance",Compact,Convertible,28,19,3916,40650,10.612754,135.500000,50.000000
2,BMW,1 Series,2011,premium unleaded (required),300.0,6.0,MANUAL,rear wheel drive,2.0,"Luxury,High-Performance",Compact,Coupe,28,20,3916,36350,10.500949,121.166667,50.000000
3,BMW,1 Series,2011,premium unleaded (required),230.0,6.0,MANUAL,rear wheel drive,2.0,"Luxury,Performance",Compact,Coupe,28,18,3916,29450,10.290449,128.043478,38.333333
4,BMW,1 Series,2011,premium unleaded (required),230.0,6.0,MANUAL,rear wheel drive,2.0,Luxury,Compact,Convertible,28,18,3916,34500,10.448715,150.000000,38.333333

In [ ]:
#missing values
df.isnull().sum()

Make                  0
Model                 0
Year                  0
Engine Fuel Type      0
Engine HP             0
Engine Cylinders      0
Transmission Type     0
Driven_Wheels         0
Number of Doors       0
Market Category       0
Vehicle Size          0
Vehicle Style         0
highway MPG           0
city mpg              0
Popularity            0
MSRP                  0
log_MSRP              0
MSRP_per_Engine_HP    0
HP_per_Cylinder       0
dtype: int64

In [ ]:
#let us select terget variable for regression task
X = df.drop("MSRP", axis=1)
y = df["MSRP"]

In [ ]:
X.shape

(11914, 18)

In [ ]:
#Splitting Data into train and test Data
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(X, y,test_size=0.2, random_state=42)

In [ ]:
print(X_train.shape)
print(y_train.shape)
print(X_test.shape)
print(y_test. shape)

(9531, 18)
(9531,)
(2383, 18)
(2383,)

In [ ]:
X_train.info()

<class 'pandas.core.frame.DataFrame'>
Index: 9531 entries, 3181 to 7270
Data columns (total 18 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Make                9531 non-null   object
 1   Model               9531 non-null   object
 2   Year                9531 non-null   int64
 3   Engine Fuel Type    9531 non-null   object
 4   Engine HP           9531 non-null   float64
 5   Engine Cylinders    9531 non-null   float64
 6   Transmission Type   9531 non-null   object
 7   Driven_Wheels       9531 non-null   object
 8   Number of Doors     9531 non-null   float64
 9   Market Category     9531 non-null   object
 10  Vehicle Size        9531 non-null   object
 11  Vehicle Style       9531 non-null   object
 12  highway MPG         9531 non-null   int64
 13  city mpg            9531 non-null   int64
 14  Popularity          9531 non-null   int64
 15  log_MSRP            9531 non-null   float64
 16  MSRP_per_Engine_HP  9531 non-null   float64
 17  HP_per_Cylinder     9531 non-null   float64
dtypes: float64(6), int64(4), object(8)
memory usage: 1.4+ MB

In [ ]:
# Separate feature names by data type
num_cols = X_train.select_dtypes(include=['int64', 'float64']).columns.tolist()
cat_cols = X_train.select_dtypes(include=['object']).columns.tolist()

print("Numerical columns:", num_cols)
print("Categorical columns:", cat_cols)

Numerical columns: ['Year', 'Engine HP', 'Engine Cylinders', 'Number of Doors', 'highway MPG', 'city mpg', 'Popularity', 'log_MSRP', 'MSRP_per_Engine_HP', 'HP_per_Cylinder']
Categorical columns: ['Make', 'Model', 'Engine Fuel Type', 'Transmission Type', 'Driven_Wheels', 'Market Category', 'Vehicle Size', 'Vehicle Style']

In [ ]:
X.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 11914 entries, 0 to 11913
Data columns (total 18 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Make                11914 non-null  object
 1   Model               11914 non-null  object
 2   Year                11914 non-null  int64
 3   Engine Fuel Type    11914 non-null  object
 4   Engine HP           11914 non-null  float64
 5   Engine Cylinders    11914 non-null  float64
 6   Transmission Type   11914 non-null  object
 7   Driven_Wheels       11914 non-null  object
 8   Number of Doors     11914 non-null  float64
 9   Market Category     11914 non-null  object
 10  Vehicle Size        11914 non-null  object
 11  Vehicle Style       11914 non-null  object
 12  highway MPG         11914 non-null  int64
 13  city mpg            11914 non-null  int64
 14  Popularity          11914 non-null  int64
 15  log_MSRP            11914 non-null  float64
 16  MSRP_per_Engine_HP  11914 non-null  float64
 17  HP_per_Cylinder     11914 non-null  float64
dtypes: float64(6), int64(4), object(8)
memory usage: 1.6+ MB

**Data Preprocessing**

In [ ]:
# Data Preprocessing
from sklearn.preprocessing import OrdinalEncoder, MinMaxScaler

# Lets use columntransformer
from sklearn. compose import ColumnTransformer
transformer=ColumnTransformer(transformers=[("t1",OrdinalEncoder(handle_unknown='use_encoded_value', unknown_value=-1), [0,1,3,6,7,9,10,11,]),
("t2",MinMaxScaler(), [2,4,5,8,12,13,14,15,16,17]) ], remainder="passthrough")

# fit_transform on train data
X_train_trans=transformer.fit_transform(X_train)

# transform on test data
X_test_trans=transformer.transform(X_test)
print(X_train_trans.shape)
print(X_test_trans.shape)

(9531, 18)
(2383, 18)

In [ ]:
X_train_trans=pd.DataFrame(X_train_trans)
X__test_trans=pd.DataFrame(X_test_trans)

In [ ]:
# let us build KNN regression Model
from sklearn.neighbors import KNeighborsRegressor
knn_model=KNeighborsRegressor()
knn_model.fit(X_train_trans,y_train)

KNeighborsRegressor()

In [ ]:
#let us make prediction using test data
y_pred=knn_model.predict(X_test_trans)

In [ ]:
# let us validate the model using r2 score
from sklearn.metrics import r2_score
r2_score(y_test,y_pred)

0.788730941096599

In [ ]:
# pipe Line BUlid
from sklearn.pipeline import Pipeline
pipe=Pipeline(steps=[("t1",transformer),("t2",KNeighborsRegressor())])
pipe.fit(X_train,y_train)

Pipeline(steps=[('t1',
                 ColumnTransformer(remainder='passthrough',
                                   transformers=[('t1',
                                                  OrdinalEncoder(handle_unknown='use_encoded_value',
                                                                 unknown_value=-1),
                                                  [0, 1, 3, 6, 7, 9, 10, 11]),
                                                 ('t2', MinMaxScaler(),
                                                  [2, 4, 5, 8, 12, 13, 14, 15,
                                                   16, 17])])),
                ('t2', KNeighborsRegressor())])

**Hyperparmeter tunning**

In [ ]:
from sklearn.model_selection import GridSearchCV

#Defining the parameter grid for KNeighborsRegressor
param_grid = {
    't2__n_neighbors': [3, 5, 7, 9, 11, 15],
    't2__weights': ['uniform', 'distance'],
    't2__metric': ['euclidean', 'manhattan']
}

#Initialize GridSearchCV
grid_search = GridSearchCV(
    estimator=pipe,
    param_grid=param_grid,
    cv=5,                      # 5-fold cross-validation
    scoring='neg_mean_absolute_error', # optimizes for MAE
    n_jobs=-1                  # use all available CPU cores
)

# 3. Fit GridSearch on training data
grid_search.fit(X_train, y_train)

# 4. View best hyperparameters and best MAE score
print("Best Parameters:", grid_search.best_params_)
print("Best Cross-Validation MAE:", -grid_search.best_score_)

# 5. Evaluate the best model on test data
best_model = grid_search.best_estimator_
y_pred_best = best_model.predict(X_test)

from sklearn.metrics import mean_absolute_error, r2_score
print("Test MAE:", mean_absolute_error(y_test, y_pred_best))
print("Test R2 Score:", r2_score(y_test, y_pred_best))

Best Parameters: {'t2__metric': 'manhattan', 't2__n_neighbors': 3, 't2__weights': 'distance'}
Best Cross-Validation MAE: 3583.7596729418715
Test MAE: 2842.9730847417154
Test R2 Score: 0.9016400919409697